### ISSUE TITLE
Pin GCC torture test revision?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/experimental#45]
`build.py` tries to read:
```
GCC_REVISION = os.environ.get('BUILDBOT_GCC_REVISION', 'None')
```
Which currently is never set, leading us to use `origin/master`. This can cause spurious breakage when the GCC torture tests are updated.

Should we pin the revision to avoid unexpected breakage, and if so how should we do it?

**Comment by dschuff** [comment]
Probably we want to pin it.

We could make gcc a submodule of the experimental repo, which has the advantage that we do that in other GH projects. The disadvantage would be that not every user of experimental may want every dependency because it's used for random unrelated stuff.

Another option would be to use (or use something like) what we have in toolchain_build_pnacl.py and pnacl/COMPONENT_REVISIONS where there's just a bit of custom code with an explicit version file.

**Comment by jfbastien** [comment]
Did a quick hack for now.
