### ISSUE TITLE
call_indirect return type is ambiguous

### ISSUE THREAD

**Issue by kripken** [WebAssembly/experimental#53]
In the current `.s` format, `call_indirect` looks like this:
````
	call_indirect	$0
	call_indirect	$push0=, $0
        etc.
````

It doesn't define the type as `.wast` files do. But, the parameter types can be inferred by what is actually seen. However, that doesn't work for the return type:

1. It could be inferred by looking *forward* to see how the `call_indirect` is actually used. But that might be an arbitrary distance forward.
2. It's especially ambiguous when the called function has a return value but it's discarded.

Perhaps `call_indirect` could specify the return type?

**Comment by sunfishcode** [comment]
Making `call_indirect` specify the type sounds right to me. I'll look into it.

**Comment by titzer** [comment]
In the binary format, call_indirect specifies an index into the signature
that describes the parameter and return type for the call site.

**Comment by kripken** [comment]
Some more thoughts:

 * I believe `call` not having a return type forces parsing to do 2 passes, that's what binaryen's `s2wasm` does currently.
 * If import declarations are removed (#48) then the same return type issue would be true for `call_import` as well.

All together, perhaps it makes sense to add a return type on all three call methods?

**Comment by sunfishcode** [comment]
Makes sense. I'll look into adding a type to plain `call` too. I think LLVM's own assembly parser will want this as well, for the same reason.

Concerning `call_import`: LLVM doesn't currently emit `call_import` because C++ doesn't know which functions are ES module imports as opposed to being imports from something that will be linked into the same instance. I vaguely imagine that the "module link" step could also convert `call` instructions to functions which end up being imports into `call_import` instructions, as wasmate.py currently does. This wouldn't work for indirect calls to imports, but I don't know how important that is.

It also depends on whether or not we even have `call_import`, which is being discussed in https://github.com/WebAssembly/design/issues/421.

**Comment by sunfishcode** [comment]
I posted a patch which adds types to `call` and `call_indirect` here: http://reviews.llvm.org/D15484

**Comment by sunfishcode** [comment]
The LLVM patch landed, and I updated wasmate.py in c3f29d2082cefee02ce43d5768f1860513aa6fb6.
